//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseReport.UI.Web.ServicoPrincipal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagem", Namespace="http://schemas.datacontract.org/2004/07/ExpenseReport.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Imagem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ImagemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeArquivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExpenseReport.UI.Web.ServicoPrincipal.RelatorioDespesa RelatorioDespesaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RelatorioDespesaIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ImagemID {
            get {
                return this.ImagemIDField;
            }
            set {
                if ((this.ImagemIDField.Equals(value) != true)) {
                    this.ImagemIDField = value;
                    this.RaisePropertyChanged("ImagemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeArquivo {
            get {
                return this.NomeArquivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeArquivoField, value) != true)) {
                    this.NomeArquivoField = value;
                    this.RaisePropertyChanged("NomeArquivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExpenseReport.UI.Web.ServicoPrincipal.RelatorioDespesa RelatorioDespesa {
            get {
                return this.RelatorioDespesaField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatorioDespesaField, value) != true)) {
                    this.RelatorioDespesaField = value;
                    this.RaisePropertyChanged("RelatorioDespesa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RelatorioDespesaID {
            get {
                return this.RelatorioDespesaIDField;
            }
            set {
                if ((this.RelatorioDespesaIDField.Equals(value) != true)) {
                    this.RelatorioDespesaIDField = value;
                    this.RaisePropertyChanged("RelatorioDespesaID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatorioDespesa", Namespace="http://schemas.datacontract.org/2004/07/ExpenseReport.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class RelatorioDespesa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FaturadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExpenseReport.UI.Web.ServicoPrincipal.FonteDespesa FonteDespesaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FonteDespesaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExpenseReport.UI.Web.ServicoPrincipal.Imagem[] ImagensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExpenseReport.UI.Web.ServicoPrincipal.Relatorio RelatorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RelatorioDespesaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RelatorioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExpenseReport.UI.Web.ServicoPrincipal.TipoDespesa TipoDespesaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TipoDespesaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Faturado {
            get {
                return this.FaturadoField;
            }
            set {
                if ((this.FaturadoField.Equals(value) != true)) {
                    this.FaturadoField = value;
                    this.RaisePropertyChanged("Faturado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExpenseReport.UI.Web.ServicoPrincipal.FonteDespesa FonteDespesa {
            get {
                return this.FonteDespesaField;
            }
            set {
                if ((object.ReferenceEquals(this.FonteDespesaField, value) != true)) {
                    this.FonteDespesaField = value;
                    this.RaisePropertyChanged("FonteDespesa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FonteDespesaID {
            get {
                return this.FonteDespesaIDField;
            }
            set {
                if ((this.FonteDespesaIDField.Equals(value) != true)) {
                    this.FonteDespesaIDField = value;
                    this.RaisePropertyChanged("FonteDespesaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExpenseReport.UI.Web.ServicoPrincipal.Imagem[] Imagens {
            get {
                return this.ImagensField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagensField, value) != true)) {
                    this.ImagensField = value;
                    this.RaisePropertyChanged("Imagens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExpenseReport.UI.Web.ServicoPrincipal.Relatorio Relatorio {
            get {
                return this.RelatorioField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatorioField, value) != true)) {
                    this.RelatorioField = value;
                    this.RaisePropertyChanged("Relatorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RelatorioDespesaID {
            get {
                return this.RelatorioDespesaIDField;
            }
            set {
                if ((this.RelatorioDespesaIDField.Equals(value) != true)) {
                    this.RelatorioDespesaIDField = value;
                    this.RaisePropertyChanged("RelatorioDespesaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RelatorioID {
            get {
                return this.RelatorioIDField;
            }
            set {
                if ((this.RelatorioIDField.Equals(value) != true)) {
                    this.RelatorioIDField = value;
                    this.RaisePropertyChanged("RelatorioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExpenseReport.UI.Web.ServicoPrincipal.TipoDespesa TipoDespesa {
            get {
                return this.TipoDespesaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDespesaField, value) != true)) {
                    this.TipoDespesaField = value;
                    this.RaisePropertyChanged("TipoDespesa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TipoDespesaID {
            get {
                return this.TipoDespesaIDField;
            }
            set {
                if ((this.TipoDespesaIDField.Equals(value) != true)) {
                    this.TipoDespesaIDField = value;
                    this.RaisePropertyChanged("TipoDespesaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FonteDespesa", Namespace="http://schemas.datacontract.org/2004/07/ExpenseReport.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class FonteDespesa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FonteDespesaIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FonteDespesaID {
            get {
                return this.FonteDespesaIDField;
            }
            set {
                if ((this.FonteDespesaIDField.Equals(value) != true)) {
                    this.FonteDespesaIDField = value;
                    this.RaisePropertyChanged("FonteDespesaID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relatorio", Namespace="http://schemas.datacontract.org/2004/07/ExpenseReport.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Relatorio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AdiantamentoRecebidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CambioDiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExpenseReport.UI.Web.ServicoPrincipal.Colaborador ColaboradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ColaboradorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataViagemFimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataViagemInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExpenseReport.UI.Web.ServicoPrincipal.RelatorioDespesa[] DespesasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DiariasRecebidasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PassagemFaturadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RelatorioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExpenseReport.UI.Web.ServicoPrincipal.Viagem ViagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ViagemIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AdiantamentoRecebido {
            get {
                return this.AdiantamentoRecebidoField;
            }
            set {
                if ((this.AdiantamentoRecebidoField.Equals(value) != true)) {
                    this.AdiantamentoRecebidoField = value;
                    this.RaisePropertyChanged("AdiantamentoRecebido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CambioDia {
            get {
                return this.CambioDiaField;
            }
            set {
                if ((this.CambioDiaField.Equals(value) != true)) {
                    this.CambioDiaField = value;
                    this.RaisePropertyChanged("CambioDia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExpenseReport.UI.Web.ServicoPrincipal.Colaborador Colaborador {
            get {
                return this.ColaboradorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColaboradorField, value) != true)) {
                    this.ColaboradorField = value;
                    this.RaisePropertyChanged("Colaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ColaboradorID {
            get {
                return this.ColaboradorIDField;
            }
            set {
                if ((this.ColaboradorIDField.Equals(value) != true)) {
                    this.ColaboradorIDField = value;
                    this.RaisePropertyChanged("ColaboradorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataEntrega {
            get {
                return this.DataEntregaField;
            }
            set {
                if ((this.DataEntregaField.Equals(value) != true)) {
                    this.DataEntregaField = value;
                    this.RaisePropertyChanged("DataEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataViagemFim {
            get {
                return this.DataViagemFimField;
            }
            set {
                if ((this.DataViagemFimField.Equals(value) != true)) {
                    this.DataViagemFimField = value;
                    this.RaisePropertyChanged("DataViagemFim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataViagemInicio {
            get {
                return this.DataViagemInicioField;
            }
            set {
                if ((this.DataViagemInicioField.Equals(value) != true)) {
                    this.DataViagemInicioField = value;
                    this.RaisePropertyChanged("DataViagemInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExpenseReport.UI.Web.ServicoPrincipal.RelatorioDespesa[] Despesas {
            get {
                return this.DespesasField;
            }
            set {
                if ((object.ReferenceEquals(this.DespesasField, value) != true)) {
                    this.DespesasField = value;
                    this.RaisePropertyChanged("Despesas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiariasRecebidas {
            get {
                return this.DiariasRecebidasField;
            }
            set {
                if ((this.DiariasRecebidasField.Equals(value) != true)) {
                    this.DiariasRecebidasField = value;
                    this.RaisePropertyChanged("DiariasRecebidas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moeda {
            get {
                return this.MoedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoedaField, value) != true)) {
                    this.MoedaField = value;
                    this.RaisePropertyChanged("Moeda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PassagemFaturada {
            get {
                return this.PassagemFaturadaField;
            }
            set {
                if ((this.PassagemFaturadaField.Equals(value) != true)) {
                    this.PassagemFaturadaField = value;
                    this.RaisePropertyChanged("PassagemFaturada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RelatorioID {
            get {
                return this.RelatorioIDField;
            }
            set {
                if ((this.RelatorioIDField.Equals(value) != true)) {
                    this.RelatorioIDField = value;
                    this.RaisePropertyChanged("RelatorioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExpenseReport.UI.Web.ServicoPrincipal.Viagem Viagem {
            get {
                return this.ViagemField;
            }
            set {
                if ((object.ReferenceEquals(this.ViagemField, value) != true)) {
                    this.ViagemField = value;
                    this.RaisePropertyChanged("Viagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ViagemID {
            get {
                return this.ViagemIDField;
            }
            set {
                if ((this.ViagemIDField.Equals(value) != true)) {
                    this.ViagemIDField = value;
                    this.RaisePropertyChanged("ViagemID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDespesa", Namespace="http://schemas.datacontract.org/2004/07/ExpenseReport.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class TipoDespesa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TipoDespesaIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TipoDespesaID {
            get {
                return this.TipoDespesaIDField;
            }
            set {
                if ((this.TipoDespesaIDField.Equals(value) != true)) {
                    this.TipoDespesaIDField = value;
                    this.RaisePropertyChanged("TipoDespesaID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Colaborador", Namespace="http://schemas.datacontract.org/2004/07/ExpenseReport.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Colaborador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ColaboradorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[] RelatoriosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TokenIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExpenseReport.UI.Web.ServicoPrincipal.Token UserTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ColaboradorID {
            get {
                return this.ColaboradorIDField;
            }
            set {
                if ((this.ColaboradorIDField.Equals(value) != true)) {
                    this.ColaboradorIDField = value;
                    this.RaisePropertyChanged("ColaboradorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[] Relatorios {
            get {
                return this.RelatoriosField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatoriosField, value) != true)) {
                    this.RelatoriosField = value;
                    this.RaisePropertyChanged("Relatorios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TokenID {
            get {
                return this.TokenIDField;
            }
            set {
                if ((this.TokenIDField.Equals(value) != true)) {
                    this.TokenIDField = value;
                    this.RaisePropertyChanged("TokenID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExpenseReport.UI.Web.ServicoPrincipal.Token UserToken {
            get {
                return this.UserTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTokenField, value) != true)) {
                    this.UserTokenField = value;
                    this.RaisePropertyChanged("UserToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Viagem", Namespace="http://schemas.datacontract.org/2004/07/ExpenseReport.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Viagem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataFimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JustificativaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExpenseReport.UI.Web.ServicoPrincipal.Projeto ProjetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProjetoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[] RelatoriosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ViagemIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataFim {
            get {
                return this.DataFimField;
            }
            set {
                if ((this.DataFimField.Equals(value) != true)) {
                    this.DataFimField = value;
                    this.RaisePropertyChanged("DataFim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataInicio {
            get {
                return this.DataInicioField;
            }
            set {
                if ((this.DataInicioField.Equals(value) != true)) {
                    this.DataInicioField = value;
                    this.RaisePropertyChanged("DataInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Justificativa {
            get {
                return this.JustificativaField;
            }
            set {
                if ((object.ReferenceEquals(this.JustificativaField, value) != true)) {
                    this.JustificativaField = value;
                    this.RaisePropertyChanged("Justificativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExpenseReport.UI.Web.ServicoPrincipal.Projeto Projeto {
            get {
                return this.ProjetoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjetoField, value) != true)) {
                    this.ProjetoField = value;
                    this.RaisePropertyChanged("Projeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProjetoID {
            get {
                return this.ProjetoIDField;
            }
            set {
                if ((this.ProjetoIDField.Equals(value) != true)) {
                    this.ProjetoIDField = value;
                    this.RaisePropertyChanged("ProjetoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[] Relatorios {
            get {
                return this.RelatoriosField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatoriosField, value) != true)) {
                    this.RelatoriosField = value;
                    this.RaisePropertyChanged("Relatorios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ViagemID {
            get {
                return this.ViagemIDField;
            }
            set {
                if ((this.ViagemIDField.Equals(value) != true)) {
                    this.ViagemIDField = value;
                    this.RaisePropertyChanged("ViagemID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Token", Namespace="http://schemas.datacontract.org/2004/07/ExpenseReport.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Token : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Projeto", Namespace="http://schemas.datacontract.org/2004/07/ExpenseReport.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Projeto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroDeCustoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProjetoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroDeCusto {
            get {
                return this.CentroDeCustoField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroDeCustoField, value) != true)) {
                    this.CentroDeCustoField = value;
                    this.RaisePropertyChanged("CentroDeCusto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Programa {
            get {
                return this.ProgramaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramaField, value) != true)) {
                    this.ProgramaField = value;
                    this.RaisePropertyChanged("Programa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProjetoID {
            get {
                return this.ProjetoIDField;
            }
            set {
                if ((this.ProjetoIDField.Equals(value) != true)) {
                    this.ProjetoIDField = value;
                    this.RaisePropertyChanged("ProjetoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoPrincipal.IServicoPrincipal")]
    public interface IServicoPrincipal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Imagem_ListagemPorRelatorioDespesa", ReplyAction="http://tempuri.org/IServicoPrincipal/Imagem_ListagemPorRelatorioDespesaResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Imagem[] Imagem_ListagemPorRelatorioDespesa(long RelatorioDespesaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Imagem_ListagemPorRelatorioDespesa", ReplyAction="http://tempuri.org/IServicoPrincipal/Imagem_ListagemPorRelatorioDespesaResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Imagem[]> Imagem_ListagemPorRelatorioDespesaAsync(long RelatorioDespesaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Imagem_Incluir", ReplyAction="http://tempuri.org/IServicoPrincipal/Imagem_IncluirResponse")]
        long Imagem_Incluir(ExpenseReport.UI.Web.ServicoPrincipal.Imagem imagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Imagem_Incluir", ReplyAction="http://tempuri.org/IServicoPrincipal/Imagem_IncluirResponse")]
        System.Threading.Tasks.Task<long> Imagem_IncluirAsync(ExpenseReport.UI.Web.ServicoPrincipal.Imagem imagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Imagem_Excluir", ReplyAction="http://tempuri.org/IServicoPrincipal/Imagem_ExcluirResponse")]
        bool Imagem_Excluir(long imagemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Imagem_Excluir", ReplyAction="http://tempuri.org/IServicoPrincipal/Imagem_ExcluirResponse")]
        System.Threading.Tasks.Task<bool> Imagem_ExcluirAsync(long imagemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Colaborador_Listagem", ReplyAction="http://tempuri.org/IServicoPrincipal/Colaborador_ListagemResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Colaborador[] Colaborador_Listagem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Colaborador_Listagem", ReplyAction="http://tempuri.org/IServicoPrincipal/Colaborador_ListagemResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Colaborador[]> Colaborador_ListagemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Colaborador_ListagemPorNome", ReplyAction="http://tempuri.org/IServicoPrincipal/Colaborador_ListagemPorNomeResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Colaborador[] Colaborador_ListagemPorNome(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Colaborador_ListagemPorNome", ReplyAction="http://tempuri.org/IServicoPrincipal/Colaborador_ListagemPorNomeResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Colaborador[]> Colaborador_ListagemPorNomeAsync(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Colaborador_PeloCodigo", ReplyAction="http://tempuri.org/IServicoPrincipal/Colaborador_PeloCodigoResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Colaborador Colaborador_PeloCodigo(long colaboradorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Colaborador_PeloCodigo", ReplyAction="http://tempuri.org/IServicoPrincipal/Colaborador_PeloCodigoResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Colaborador> Colaborador_PeloCodigoAsync(long colaboradorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/FonteDespesa_Listagem", ReplyAction="http://tempuri.org/IServicoPrincipal/FonteDespesa_ListagemResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.FonteDespesa[] FonteDespesa_Listagem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/FonteDespesa_Listagem", ReplyAction="http://tempuri.org/IServicoPrincipal/FonteDespesa_ListagemResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.FonteDespesa[]> FonteDespesa_ListagemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/TipoDespesa_Listagem", ReplyAction="http://tempuri.org/IServicoPrincipal/TipoDespesa_ListagemResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.TipoDespesa[] TipoDespesa_Listagem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/TipoDespesa_Listagem", ReplyAction="http://tempuri.org/IServicoPrincipal/TipoDespesa_ListagemResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.TipoDespesa[]> TipoDespesa_ListagemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Viagem_Listagem", ReplyAction="http://tempuri.org/IServicoPrincipal/Viagem_ListagemResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Viagem[] Viagem_Listagem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Viagem_Listagem", ReplyAction="http://tempuri.org/IServicoPrincipal/Viagem_ListagemResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Viagem[]> Viagem_ListagemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Viagem_ListagemPorDescricao", ReplyAction="http://tempuri.org/IServicoPrincipal/Viagem_ListagemPorDescricaoResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Viagem[] Viagem_ListagemPorDescricao(string Descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Viagem_ListagemPorDescricao", ReplyAction="http://tempuri.org/IServicoPrincipal/Viagem_ListagemPorDescricaoResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Viagem[]> Viagem_ListagemPorDescricaoAsync(string Descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Viagem_ListagemPorProjeto", ReplyAction="http://tempuri.org/IServicoPrincipal/Viagem_ListagemPorProjetoResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Viagem[] Viagem_ListagemPorProjeto(long ProjetoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Viagem_ListagemPorProjeto", ReplyAction="http://tempuri.org/IServicoPrincipal/Viagem_ListagemPorProjetoResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Viagem[]> Viagem_ListagemPorProjetoAsync(long ProjetoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Viagem_Excluir", ReplyAction="http://tempuri.org/IServicoPrincipal/Viagem_ExcluirResponse")]
        bool Viagem_Excluir(long ViagemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Viagem_Excluir", ReplyAction="http://tempuri.org/IServicoPrincipal/Viagem_ExcluirResponse")]
        System.Threading.Tasks.Task<bool> Viagem_ExcluirAsync(long ViagemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Viagem_Incluir", ReplyAction="http://tempuri.org/IServicoPrincipal/Viagem_IncluirResponse")]
        long Viagem_Incluir(ExpenseReport.UI.Web.ServicoPrincipal.Viagem viagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Viagem_Incluir", ReplyAction="http://tempuri.org/IServicoPrincipal/Viagem_IncluirResponse")]
        System.Threading.Tasks.Task<long> Viagem_IncluirAsync(ExpenseReport.UI.Web.ServicoPrincipal.Viagem viagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Viagem_Alterar", ReplyAction="http://tempuri.org/IServicoPrincipal/Viagem_AlterarResponse")]
        bool Viagem_Alterar(ExpenseReport.UI.Web.ServicoPrincipal.Viagem viagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Viagem_Alterar", ReplyAction="http://tempuri.org/IServicoPrincipal/Viagem_AlterarResponse")]
        System.Threading.Tasks.Task<bool> Viagem_AlterarAsync(ExpenseReport.UI.Web.ServicoPrincipal.Viagem viagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Viagem_PorID", ReplyAction="http://tempuri.org/IServicoPrincipal/Viagem_PorIDResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Viagem Viagem_PorID(long ViagemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Viagem_PorID", ReplyAction="http://tempuri.org/IServicoPrincipal/Viagem_PorIDResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Viagem> Viagem_PorIDAsync(long ViagemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/RelatorioDespesa_ListagemPorRelatorio", ReplyAction="http://tempuri.org/IServicoPrincipal/RelatorioDespesa_ListagemPorRelatorioRespons" +
            "e")]
        ExpenseReport.UI.Web.ServicoPrincipal.RelatorioDespesa[] RelatorioDespesa_ListagemPorRelatorio(long relatorioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/RelatorioDespesa_ListagemPorRelatorio", ReplyAction="http://tempuri.org/IServicoPrincipal/RelatorioDespesa_ListagemPorRelatorioRespons" +
            "e")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.RelatorioDespesa[]> RelatorioDespesa_ListagemPorRelatorioAsync(long relatorioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/RelatorioDespesa_Incluir", ReplyAction="http://tempuri.org/IServicoPrincipal/RelatorioDespesa_IncluirResponse")]
        long RelatorioDespesa_Incluir(ExpenseReport.UI.Web.ServicoPrincipal.RelatorioDespesa relatorioDespesa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/RelatorioDespesa_Incluir", ReplyAction="http://tempuri.org/IServicoPrincipal/RelatorioDespesa_IncluirResponse")]
        System.Threading.Tasks.Task<long> RelatorioDespesa_IncluirAsync(ExpenseReport.UI.Web.ServicoPrincipal.RelatorioDespesa relatorioDespesa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/RelatorioDespesa_Excluir", ReplyAction="http://tempuri.org/IServicoPrincipal/RelatorioDespesa_ExcluirResponse")]
        bool RelatorioDespesa_Excluir(long RelatorioDespesaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/RelatorioDespesa_Excluir", ReplyAction="http://tempuri.org/IServicoPrincipal/RelatorioDespesa_ExcluirResponse")]
        System.Threading.Tasks.Task<bool> RelatorioDespesa_ExcluirAsync(long RelatorioDespesaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPorData", ReplyAction="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPorDataResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[] Relatorio_ListagemPorData(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPorData", ReplyAction="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPorDataResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[]> Relatorio_ListagemPorDataAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPorColaborador", ReplyAction="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPorColaboradorResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[] Relatorio_ListagemPorColaborador(long colaboradorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPorColaborador", ReplyAction="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPorColaboradorResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[]> Relatorio_ListagemPorColaboradorAsync(long colaboradorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPorDataColaborador", ReplyAction="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPorDataColaboradorResponse" +
            "")]
        ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[] Relatorio_ListagemPorDataColaborador(System.DateTime data, long colaboradorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPorDataColaborador", ReplyAction="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPorDataColaboradorResponse" +
            "")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[]> Relatorio_ListagemPorDataColaboradorAsync(System.DateTime data, long colaboradorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPoDescricaoViagem", ReplyAction="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPoDescricaoViagemResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[] Relatorio_ListagemPoDescricaoViagem(string descricaoViagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPoDescricaoViagem", ReplyAction="http://tempuri.org/IServicoPrincipal/Relatorio_ListagemPoDescricaoViagemResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[]> Relatorio_ListagemPoDescricaoViagemAsync(string descricaoViagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Relatorio_Incluir", ReplyAction="http://tempuri.org/IServicoPrincipal/Relatorio_IncluirResponse")]
        long Relatorio_Incluir(ExpenseReport.UI.Web.ServicoPrincipal.Relatorio relatorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Relatorio_Incluir", ReplyAction="http://tempuri.org/IServicoPrincipal/Relatorio_IncluirResponse")]
        System.Threading.Tasks.Task<long> Relatorio_IncluirAsync(ExpenseReport.UI.Web.ServicoPrincipal.Relatorio relatorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Relatorio_Alterar", ReplyAction="http://tempuri.org/IServicoPrincipal/Relatorio_AlterarResponse")]
        bool Relatorio_Alterar(ExpenseReport.UI.Web.ServicoPrincipal.Relatorio relatorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Relatorio_Alterar", ReplyAction="http://tempuri.org/IServicoPrincipal/Relatorio_AlterarResponse")]
        System.Threading.Tasks.Task<bool> Relatorio_AlterarAsync(ExpenseReport.UI.Web.ServicoPrincipal.Relatorio relatorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Relatorio_PorId", ReplyAction="http://tempuri.org/IServicoPrincipal/Relatorio_PorIdResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Relatorio Relatorio_PorId(long RelatorioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Relatorio_PorId", ReplyAction="http://tempuri.org/IServicoPrincipal/Relatorio_PorIdResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Relatorio> Relatorio_PorIdAsync(long RelatorioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Projeto_Listagem", ReplyAction="http://tempuri.org/IServicoPrincipal/Projeto_ListagemResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Projeto[] Projeto_Listagem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Projeto_Listagem", ReplyAction="http://tempuri.org/IServicoPrincipal/Projeto_ListagemResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Projeto[]> Projeto_ListagemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Projeto_ListagemPorDescricao", ReplyAction="http://tempuri.org/IServicoPrincipal/Projeto_ListagemPorDescricaoResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Projeto[] Projeto_ListagemPorDescricao(string Descrica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Projeto_ListagemPorDescricao", ReplyAction="http://tempuri.org/IServicoPrincipal/Projeto_ListagemPorDescricaoResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Projeto[]> Projeto_ListagemPorDescricaoAsync(string Descrica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Projeto_Excluir", ReplyAction="http://tempuri.org/IServicoPrincipal/Projeto_ExcluirResponse")]
        bool Projeto_Excluir(long ProjetoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Projeto_Excluir", ReplyAction="http://tempuri.org/IServicoPrincipal/Projeto_ExcluirResponse")]
        System.Threading.Tasks.Task<bool> Projeto_ExcluirAsync(long ProjetoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Projeto_Incluir", ReplyAction="http://tempuri.org/IServicoPrincipal/Projeto_IncluirResponse")]
        long Projeto_Incluir(ExpenseReport.UI.Web.ServicoPrincipal.Projeto projeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Projeto_Incluir", ReplyAction="http://tempuri.org/IServicoPrincipal/Projeto_IncluirResponse")]
        System.Threading.Tasks.Task<long> Projeto_IncluirAsync(ExpenseReport.UI.Web.ServicoPrincipal.Projeto projeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Projeto_Alterar", ReplyAction="http://tempuri.org/IServicoPrincipal/Projeto_AlterarResponse")]
        bool Projeto_Alterar(ExpenseReport.UI.Web.ServicoPrincipal.Projeto projeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Projeto_Alterar", ReplyAction="http://tempuri.org/IServicoPrincipal/Projeto_AlterarResponse")]
        System.Threading.Tasks.Task<bool> Projeto_AlterarAsync(ExpenseReport.UI.Web.ServicoPrincipal.Projeto projeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Projeto_PorID", ReplyAction="http://tempuri.org/IServicoPrincipal/Projeto_PorIDResponse")]
        ExpenseReport.UI.Web.ServicoPrincipal.Projeto Projeto_PorID(long ProjetoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoPrincipal/Projeto_PorID", ReplyAction="http://tempuri.org/IServicoPrincipal/Projeto_PorIDResponse")]
        System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Projeto> Projeto_PorIDAsync(long ProjetoID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoPrincipalChannel : ExpenseReport.UI.Web.ServicoPrincipal.IServicoPrincipal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoPrincipalClient : System.ServiceModel.ClientBase<ExpenseReport.UI.Web.ServicoPrincipal.IServicoPrincipal>, ExpenseReport.UI.Web.ServicoPrincipal.IServicoPrincipal {
        
        public ServicoPrincipalClient() {
        }
        
        public ServicoPrincipalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoPrincipalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoPrincipalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoPrincipalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Imagem[] Imagem_ListagemPorRelatorioDespesa(long RelatorioDespesaID) {
            return base.Channel.Imagem_ListagemPorRelatorioDespesa(RelatorioDespesaID);
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Imagem[]> Imagem_ListagemPorRelatorioDespesaAsync(long RelatorioDespesaID) {
            return base.Channel.Imagem_ListagemPorRelatorioDespesaAsync(RelatorioDespesaID);
        }
        
        public long Imagem_Incluir(ExpenseReport.UI.Web.ServicoPrincipal.Imagem imagem) {
            return base.Channel.Imagem_Incluir(imagem);
        }
        
        public System.Threading.Tasks.Task<long> Imagem_IncluirAsync(ExpenseReport.UI.Web.ServicoPrincipal.Imagem imagem) {
            return base.Channel.Imagem_IncluirAsync(imagem);
        }
        
        public bool Imagem_Excluir(long imagemID) {
            return base.Channel.Imagem_Excluir(imagemID);
        }
        
        public System.Threading.Tasks.Task<bool> Imagem_ExcluirAsync(long imagemID) {
            return base.Channel.Imagem_ExcluirAsync(imagemID);
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Colaborador[] Colaborador_Listagem() {
            return base.Channel.Colaborador_Listagem();
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Colaborador[]> Colaborador_ListagemAsync() {
            return base.Channel.Colaborador_ListagemAsync();
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Colaborador[] Colaborador_ListagemPorNome(string nome) {
            return base.Channel.Colaborador_ListagemPorNome(nome);
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Colaborador[]> Colaborador_ListagemPorNomeAsync(string nome) {
            return base.Channel.Colaborador_ListagemPorNomeAsync(nome);
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Colaborador Colaborador_PeloCodigo(long colaboradorID) {
            return base.Channel.Colaborador_PeloCodigo(colaboradorID);
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Colaborador> Colaborador_PeloCodigoAsync(long colaboradorID) {
            return base.Channel.Colaborador_PeloCodigoAsync(colaboradorID);
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.FonteDespesa[] FonteDespesa_Listagem() {
            return base.Channel.FonteDespesa_Listagem();
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.FonteDespesa[]> FonteDespesa_ListagemAsync() {
            return base.Channel.FonteDespesa_ListagemAsync();
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.TipoDespesa[] TipoDespesa_Listagem() {
            return base.Channel.TipoDespesa_Listagem();
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.TipoDespesa[]> TipoDespesa_ListagemAsync() {
            return base.Channel.TipoDespesa_ListagemAsync();
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Viagem[] Viagem_Listagem() {
            return base.Channel.Viagem_Listagem();
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Viagem[]> Viagem_ListagemAsync() {
            return base.Channel.Viagem_ListagemAsync();
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Viagem[] Viagem_ListagemPorDescricao(string Descricao) {
            return base.Channel.Viagem_ListagemPorDescricao(Descricao);
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Viagem[]> Viagem_ListagemPorDescricaoAsync(string Descricao) {
            return base.Channel.Viagem_ListagemPorDescricaoAsync(Descricao);
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Viagem[] Viagem_ListagemPorProjeto(long ProjetoID) {
            return base.Channel.Viagem_ListagemPorProjeto(ProjetoID);
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Viagem[]> Viagem_ListagemPorProjetoAsync(long ProjetoID) {
            return base.Channel.Viagem_ListagemPorProjetoAsync(ProjetoID);
        }
        
        public bool Viagem_Excluir(long ViagemID) {
            return base.Channel.Viagem_Excluir(ViagemID);
        }
        
        public System.Threading.Tasks.Task<bool> Viagem_ExcluirAsync(long ViagemID) {
            return base.Channel.Viagem_ExcluirAsync(ViagemID);
        }
        
        public long Viagem_Incluir(ExpenseReport.UI.Web.ServicoPrincipal.Viagem viagem) {
            return base.Channel.Viagem_Incluir(viagem);
        }
        
        public System.Threading.Tasks.Task<long> Viagem_IncluirAsync(ExpenseReport.UI.Web.ServicoPrincipal.Viagem viagem) {
            return base.Channel.Viagem_IncluirAsync(viagem);
        }
        
        public bool Viagem_Alterar(ExpenseReport.UI.Web.ServicoPrincipal.Viagem viagem) {
            return base.Channel.Viagem_Alterar(viagem);
        }
        
        public System.Threading.Tasks.Task<bool> Viagem_AlterarAsync(ExpenseReport.UI.Web.ServicoPrincipal.Viagem viagem) {
            return base.Channel.Viagem_AlterarAsync(viagem);
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Viagem Viagem_PorID(long ViagemID) {
            return base.Channel.Viagem_PorID(ViagemID);
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Viagem> Viagem_PorIDAsync(long ViagemID) {
            return base.Channel.Viagem_PorIDAsync(ViagemID);
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.RelatorioDespesa[] RelatorioDespesa_ListagemPorRelatorio(long relatorioID) {
            return base.Channel.RelatorioDespesa_ListagemPorRelatorio(relatorioID);
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.RelatorioDespesa[]> RelatorioDespesa_ListagemPorRelatorioAsync(long relatorioID) {
            return base.Channel.RelatorioDespesa_ListagemPorRelatorioAsync(relatorioID);
        }
        
        public long RelatorioDespesa_Incluir(ExpenseReport.UI.Web.ServicoPrincipal.RelatorioDespesa relatorioDespesa) {
            return base.Channel.RelatorioDespesa_Incluir(relatorioDespesa);
        }
        
        public System.Threading.Tasks.Task<long> RelatorioDespesa_IncluirAsync(ExpenseReport.UI.Web.ServicoPrincipal.RelatorioDespesa relatorioDespesa) {
            return base.Channel.RelatorioDespesa_IncluirAsync(relatorioDespesa);
        }
        
        public bool RelatorioDespesa_Excluir(long RelatorioDespesaID) {
            return base.Channel.RelatorioDespesa_Excluir(RelatorioDespesaID);
        }
        
        public System.Threading.Tasks.Task<bool> RelatorioDespesa_ExcluirAsync(long RelatorioDespesaID) {
            return base.Channel.RelatorioDespesa_ExcluirAsync(RelatorioDespesaID);
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[] Relatorio_ListagemPorData(System.DateTime data) {
            return base.Channel.Relatorio_ListagemPorData(data);
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[]> Relatorio_ListagemPorDataAsync(System.DateTime data) {
            return base.Channel.Relatorio_ListagemPorDataAsync(data);
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[] Relatorio_ListagemPorColaborador(long colaboradorID) {
            return base.Channel.Relatorio_ListagemPorColaborador(colaboradorID);
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[]> Relatorio_ListagemPorColaboradorAsync(long colaboradorID) {
            return base.Channel.Relatorio_ListagemPorColaboradorAsync(colaboradorID);
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[] Relatorio_ListagemPorDataColaborador(System.DateTime data, long colaboradorID) {
            return base.Channel.Relatorio_ListagemPorDataColaborador(data, colaboradorID);
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[]> Relatorio_ListagemPorDataColaboradorAsync(System.DateTime data, long colaboradorID) {
            return base.Channel.Relatorio_ListagemPorDataColaboradorAsync(data, colaboradorID);
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[] Relatorio_ListagemPoDescricaoViagem(string descricaoViagem) {
            return base.Channel.Relatorio_ListagemPoDescricaoViagem(descricaoViagem);
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Relatorio[]> Relatorio_ListagemPoDescricaoViagemAsync(string descricaoViagem) {
            return base.Channel.Relatorio_ListagemPoDescricaoViagemAsync(descricaoViagem);
        }
        
        public long Relatorio_Incluir(ExpenseReport.UI.Web.ServicoPrincipal.Relatorio relatorio) {
            return base.Channel.Relatorio_Incluir(relatorio);
        }
        
        public System.Threading.Tasks.Task<long> Relatorio_IncluirAsync(ExpenseReport.UI.Web.ServicoPrincipal.Relatorio relatorio) {
            return base.Channel.Relatorio_IncluirAsync(relatorio);
        }
        
        public bool Relatorio_Alterar(ExpenseReport.UI.Web.ServicoPrincipal.Relatorio relatorio) {
            return base.Channel.Relatorio_Alterar(relatorio);
        }
        
        public System.Threading.Tasks.Task<bool> Relatorio_AlterarAsync(ExpenseReport.UI.Web.ServicoPrincipal.Relatorio relatorio) {
            return base.Channel.Relatorio_AlterarAsync(relatorio);
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Relatorio Relatorio_PorId(long RelatorioID) {
            return base.Channel.Relatorio_PorId(RelatorioID);
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Relatorio> Relatorio_PorIdAsync(long RelatorioID) {
            return base.Channel.Relatorio_PorIdAsync(RelatorioID);
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Projeto[] Projeto_Listagem() {
            return base.Channel.Projeto_Listagem();
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Projeto[]> Projeto_ListagemAsync() {
            return base.Channel.Projeto_ListagemAsync();
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Projeto[] Projeto_ListagemPorDescricao(string Descrica) {
            return base.Channel.Projeto_ListagemPorDescricao(Descrica);
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Projeto[]> Projeto_ListagemPorDescricaoAsync(string Descrica) {
            return base.Channel.Projeto_ListagemPorDescricaoAsync(Descrica);
        }
        
        public bool Projeto_Excluir(long ProjetoID) {
            return base.Channel.Projeto_Excluir(ProjetoID);
        }
        
        public System.Threading.Tasks.Task<bool> Projeto_ExcluirAsync(long ProjetoID) {
            return base.Channel.Projeto_ExcluirAsync(ProjetoID);
        }
        
        public long Projeto_Incluir(ExpenseReport.UI.Web.ServicoPrincipal.Projeto projeto) {
            return base.Channel.Projeto_Incluir(projeto);
        }
        
        public System.Threading.Tasks.Task<long> Projeto_IncluirAsync(ExpenseReport.UI.Web.ServicoPrincipal.Projeto projeto) {
            return base.Channel.Projeto_IncluirAsync(projeto);
        }
        
        public bool Projeto_Alterar(ExpenseReport.UI.Web.ServicoPrincipal.Projeto projeto) {
            return base.Channel.Projeto_Alterar(projeto);
        }
        
        public System.Threading.Tasks.Task<bool> Projeto_AlterarAsync(ExpenseReport.UI.Web.ServicoPrincipal.Projeto projeto) {
            return base.Channel.Projeto_AlterarAsync(projeto);
        }
        
        public ExpenseReport.UI.Web.ServicoPrincipal.Projeto Projeto_PorID(long ProjetoID) {
            return base.Channel.Projeto_PorID(ProjetoID);
        }
        
        public System.Threading.Tasks.Task<ExpenseReport.UI.Web.ServicoPrincipal.Projeto> Projeto_PorIDAsync(long ProjetoID) {
            return base.Channel.Projeto_PorIDAsync(ProjetoID);
        }
    }
}
